const BOOK_GENRES = [
    "fiction",
    "non-fiction",
    "fantasy",
    "sci-fi",
    "mystery",
    "romance",
    "thriller",
    "historical",
    "biography",
    "poetry",
    "self-help",
    "horror",
    "drama",
    "dystopian",
    "adventure",
    "comedy",
    "spirituality",
    "literary",
    "reading",
    "lifestyle",
    "contemporary",
    "diversity",
    "philosophy",
    "science",
    "psychology",
    "young-adult",
    "children",
    "classic",
    "graphic-novel",
    "memoir",
    "education",
    "community",
    "others"
];

export const GENRES = Object.freeze(BOOK_GENRES);